---
date: '`r format(Sys.Date(), "%B %d, %Y")`'
title: Curriculum Vitae
---

# Teaching/Research Interests
Applied Computing (R, Stata, Julia), Applied Data Science, Literate Programming, Pension Economics

# Education
## The University of Texas at Dallas
*2015 December* 

* Master of Science in Economics, 3.704 GPA  

* Graduate Certificate in Economic & Demographic Data Analysis  

*2014 May*

* Bachelor of Science in Economics  

# Employment
## Statistical Consultant | Self-employed
*2016 January – Present*

* Promoted evidence-based research by writing statistical reports grounded on economic, agricultural, and public health data.

* Restructured datasets of 10,000+ observations and 100+ variables to ensure the quantitative methods generated valid estimations.

* Developed programming scripts in R, Stata, and SPSS to facilitate reproducible results for social scientists.

* Accumulated 200+ hours of tutoring with a 4.9 / 5.0 overall rating on WyzAnt in R, Stata, statistics, and econometrics for regression modeling and data management.

## Research Analyst IRO | Collin College
*2019 April – 2019 November*

* Automated via R/R Markdown a semesterly report averaging 60+ pages of frequency distribution tables.
      
* Written an Argos query and developed R loops to determine the number of contact hours generated by students enrolling after their courses' census date.
      
* Designed a questionnaire of 20+ items in the Snap Surveys software with my supervisor to inquire about communication preferences among Collin College employees.
      
* Prepared a slide deck to teach co-workers introductory data management in the R programming language, including importing, aggregating, and recoding data with the tidyverse packages. 

## Research Analyst | Collin College
*2018 January – 2019 April*

* Increased data cleaning efficiency by 67% by creating an R script with 3 custom functions to merge, deduplicate, and correct discrepancies.
      
* Refactored existing R code for classroom utilization graphs to reduce the number of scripts from 12 to 3, producing alongside a Power BI equivalent.
      
* Extracted via SQL over 1,000 records of students with AP-credited courses in the 2016-2017 academic year for the THECB to comply with H.B. 1992.
      
* Constructed an Excel dashboard of tables and comparison charts  to report monthly registration headcounts and contact hours by division on continuing education students.

      
## Jr. Business Analyst | HireGenics (Client: J.C. Penney)
*2017 April – 2017 August*

* Performed summary computations on 3 years of transactional data with R, SQL, and Datameer to track product-level sales and costs.

* Assisted in pricing experiment efforts that resulted in a 40% increase in MUNS across 25,000 products, with 33% being the expectation.

* Analyzed two weeks of hourly conversion rates for 4,000 products to determine the company-wide impact of mid-week and weekend events.

* Advanced analytical standards by testing the effects of city-level weather conditions on overall e-commerce sales via autoregressive models with distributed lags.

## Analyst | Schnitman & Associates, Inc.
*2007 September – 2015 June*

* Executed money transfers and disbursement requests according to the client's 401(k) plan with Schwab Retirement Technologies®. Evaluated cash flows to check sufficiency of reserved funds. Performed daily cash reconciliation.

* Served as an editor of distribution request forms, Plan Specifications, and participant statements to ensure consistency and increase readability.

* Maintained participant information for record-keeping purposes.

* Assisted CEO in treasury functions by tracking revenues and expenses.

* Trained new employees to process money transfers, complete distribution requests, and conduct the daily operations of the firm.

# Publications 

1. 2020 Schnitman, R. Handbook for the `dm` R Package. https://rs-dm.netlify.com/

1. 2020 Schnitman, R. A Short Introduction to Applied Statistical Programming in R. https://rs-aspr.netlify.com/

1. 2020 Schnitman, R. Handbook for the `diagnoser` R Package. https://rs-diagnoser.netlify.com/

1. 2020 Schnitman, R. Data Science and Beyblades. https://robertschnitman.netlify.com/2020/03/25/data-science-and-beyblades

1. 2020 Schnitman, R. The Narrator and the Noise: The Use of Statistical Bias in a Minigame to Emphasize a Thematic Outcome in Act 1 of Doki Doki Literature Club. https://rs-ddlc.netlify.com

1. 2020 Schnitman, R. Using the R Programming Language to Report the Sachse, TX January 2020 Special Election Pre-runoff Results. https://rs-sachse2020.netlify.com/

1. 2020 Schnitman, R. Handbook for the `afp` R Package. https://rs-afp.netlify.com/

1. 2020 Schnitman, R. OLS in R Tutorial. GitHub. https://github.com/robertschnitman/RS_Reports/blob/master/Tutorials/R%20OLS%20Tutorial.pdf

1. 2019 Schnitman, R. TukeyHSD in R Tutorial. GitHub. https://github.com/robertschnitman/RS_Reports/blob/master/Tutorials/R%20TukeyHSD%20Tutorial.pdf

1. 2015 Schnitman, R. International Confidence and Retiree Welfare: Effects of Foreign Direct Investment in the United States on Pension and Social Insurance Contributions. Academia.edu. https://www.academia.edu/19789042/International_Confidence_and_Retiree_Welfare_Effects_of_Foreign_Direct_Investment_in_the_United_States_on_Pension_and_Social_Insurance_Contributions

1. 2015 Schnitman, R. Incentivizing Labor Productivity through Pension Contributions: A Time-Series Approach with Annual Data, 1929-2014. Academia.edu. https://www.academia.edu/19789101/Incentivizing_Labor_Productivity_through_Pension_Contributions_A_Time-Series_Approach_with_Annual_Data_1929-2014

1. 2015 Schnitman, R. The Effects of Employer Contributions on the Labor Force Participation Rate over Time. Academia.edu. https://www.academia.edu/12373461/The_Effects_of_Employer_Contributions_on_the_Labor_Force_Participation_Rate_in_the_United_States_over_Time

1. 2015 Schnitman, R. Pension Portfolio Preferences since the Great Recession. Academia.edu. https://www.academia.edu/12373438/Pension_Portfolio_Preferences_since_the_Great_Recession

1. 2014 Schnitman, R. An SEM Approach to Examine the Effects of Defined Contribution Plans and Socioeconomic Status on Portfolio Preferences. Academia.edu. https://www.academia.edu/10519927/An_SEM_Approach_to_Examine_the_Effects_of_Defined_Contribution_Plans_and_Socioeconomic_Status_on_Portfolio_Preferences

1. 2013 Schnitman, R. Effects of Education, Health Behavior, and Media Consumption on Cigarette Demand. Academia.edu. https://www.academia.edu/5826780/Effects_of_Education_Health_Behavior_and_Media_Consumption_on_Cigarette_Demand

1. 2012 Schnitman, R. Cluster Analysis on the Effects of US Family Income and Human Capital on Bond-and Stock-allocation under Pension Restrictions in 1992. Academia.edu. https://www.academia.edu/5826779/Cluster_Analysis_on_the_Effects_of_US_Family_Income_and_Human_Capital_on_Bond-and_Stock-allocation_under_Pension_Restrictions_in_1992

1. 2011 Schnitman, R. Ignoratio Elenchi: Faith and Reason in Robert Louis Stevenson's Dr. Jekyll and Mr. Hyde. Academia.edu. https://www.academia.edu/41688127/Ignoratio_Elenchi_Faith_and_Reason_in_Robert_Louis_Stevensons_Dr._Jekyll_and_Mr._Hyde

# Acknowledgment

1. 2016 Arocha, D. Characteristics of Adult ICU Patients with Device Associated Nosocomial Infections. Walden University.

# Software

1. 2020 Schnitman, R. dm: Data management tools for R as inspired by Stata, SPSS, and other software. https://github.com/robertschnitman/dm

1. 2020 Schnitman, R. Price Analysis of Select Funds, 2007-2019. https://robertschnitman.shinyapps.io/funds/

1. 2019 Schnitman, R. Scatterplots with the Gapminder Dataset.  https://robertschnitman.shinyapps.io/scatter/

1. 2018 Schnitman, R. afpj: Applied Functional Programming in Julia. https://github.com/robertschnitman/afpj

1. 2018 Schnitman, R. afp: Applied Functional Programming. https://github.com/robertschnitman/afp

1. 2018 Schnitman, R. diagnoserjl: Residual Diagnostic Tools for Julia. https://github.com/robertschnitman/diagnoserjl

1. 2017 Schnitman, R. diagnoser: Residual Diagnostic Tools. https://github.com/robertschnitman/diagnoser

# Works-in-Progress

1. 2019 Schnitman, R. afpp: Applied Functional Programming in Python. https://github.com/robertschnitman/afpp

1. 2019 Schnitman, R. diagnoserpy: Residual Diagnostic Tools in Python. https://github.com/robertschnitman/diagnoserpy

# Organizations

1. 2017-Present American Economic Association, Member

1. 2015-2015 Consulting Club, University of Texas at Dallas, Member

1. 2013-2015 Delta Epsilon Iota Academic Honor Society, Member

1. 2013-2015 Omicron Delta Epsilon, Member

# Honors and Awards

1. 2017-2017 Certificate of Completion: Ruby, SoloLearn

1. 2017-2017 Certificate of Completion: Python 3, SoloLearn

1. 2016-2016 Certificate of Completion: SQL Fundamentals, SoloLearn 

1. 2014-2015 Fast-track status, EPPS, the University of Texas at Dallas

1. 2011-2012 Merit Scholarship, Cairn University (Formerly Philadelphia Biblical University)

1. 2011-2011 Dean’s List, Collin College